### ISSUE TITLE
Hot Reloading

### ISSUE THREAD

**Issue by pheuter** [pheuter/essential-react#1]
Would be nice to implement the React Hot [Loader](https://github.com/gaearon/react-hot-loader) as part of the `watch` process.
- http://gaearon.github.io/react-hot-loader/getstarted/

**Comment by dstroot** [comment]
Yes please!

**Comment by carlosvillu** [comment]
Will you switch from Browserify to WebPack ?!

**Comment by pheuter** [comment]
Will be part of #6
