### ISSUE TITLE
add basic flux

### ISSUE THREAD

**Issue by venil7** [pheuter/essential-react#10]
add basic flux

**Comment by pheuter** [comment]
I haven't had the chance yet to dive deeply into the flux architecture, even less so play around with the different implementations[1] out there. Ultimately, I don't mind adding a basic flux architecture to Essential React, as long as the core philosophy of minimalism is adhered to. The problem I feel with Flux is that it quickly gets out of hand with various different components and directory structures.

The goal with Essential React is to have as few components and moving pieces as possible to provide a skeleton for building more complex apps on top of. So, if you'd want to add a flux architecture on top of the skeleton, you'd be able to do so with relative ease. However, I am wary of providing a flux architecture out-of-the-box with the skeleton, unless it is truly simple and minimal.

[1] - https://github.com/voronianski/flux-comparison

**Comment by alanrsoares** [comment]
I could add an implementation of [alt](http://goatslacker.github.io/alt/)?
I'm using it and it's relatively minimal and clean in comparison with facebook Flux. Also it
 plays nicely with ES6.

**Comment by dmitry** [comment]
@alanrsoares that would be nice! :+1:

**Comment by pheuter** [comment]
Closing issue, sticking to one of the project's design goals of not implementing flux and instead leaving it up to users / forkers to add on top of the basic skeleton.
