### ISSUE TITLE
Images in readme.md are broken

### ISSUE THREAD

**Issue by therealmarv** [pheuter/essential-react#18]
The broken images all point to dropbox.

Solution proposal:
Maybe upload to imgur or even to the repo itself and pointing relative to it?!

**Comment by pheuter** [comment]
Hm, I still see the images rendering just fine, can anyone else confirm they are no longer seeing images in the README ?

**Comment by therealmarv** [comment]
strange. Also not broken here anymore. So maybe it was a temporal problem yesterday only.

**Comment by pheuter** [comment]
Might be a temporary CDN issue on GitHub's side, since they cache image links on their end. Closing.
