### ISSUE TITLE
[Question] Measure code coverage on JSX, not on transpiled JS

### ISSUE THREAD

**Issue by claudiopro** [pheuter/essential-react#23]
This is more a question rather than an issue. I am struggling to find a configuration that allows me to measure code coverage on the JSX source. This project shows coverage on the code transpiled from JSX by babel. Would you know if it is even possible to measure coverage on the original JSX source?

**Comment by pheuter** [comment]
The new `ava` and `nyc` test runner and code coverage tools that master has (and will be released with v0.4.0) should do proper coverage on original source code.

**Comment by claudiopro** [comment]
Thanks, I'll give them a try. I haven't used Sindre's `ava` yet so I'm quite eager to put it to a test.
