### ISSUE TITLE
Switch over to using Webpack instead of Browserify

### ISSUE THREAD

**Issue by pheuter** [pheuter/essential-react#3]
Been hearing good things about Webpack, including a nice integration with the [Hot Loader](https://github.com/gaearon/react-hot-loader). Will assess potential to switch over from Browserify.

_Note: This should minimally, if at all, affect the interface of the skeleton_
- https://github.com/petehunt/webpack-howto
- https://gist.github.com/substack/68f8d502be42d5cd4942

**Edit:** Created a new [branch](https://github.com/pheuter/essential-react/tree/webpack) where I will be making progress towards switching over to use Webpack. The core philosophy of minimal tooling is being respected as always. Minimal, if any, changes to the skeleton interface will be introduced.

**Comment by dstroot** [comment]
Yes please!

**Comment by kylehotchkiss** [comment]
:+1:

**Comment by pheuter** [comment]
Started making progress in the [webpack](https://github.com/pheuter/essential-react/tree/webpack) branch.

**Comment by pheuter** [comment]
Closing in favor of pr #6
