### ISSUE TITLE
Warning: It looks like you're using a minified copy of the development build of React. 

### ISSUE THREAD

**Issue by harlantwood** [pheuter/essential-react#43]
After updating all packages (#42), I noticed this big red warning in the JS console, when viewing the _production_ version (made with `npm run build`):

> Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.

Not sure if this was an issue before #42 or not.

**Comment by wuyanan** [comment]
I alse have the same question. Did you ever resolve it?

**Comment by harlantwood** [comment]
Seems like this was a red herring caused by some kind of bad state... not sure what the issue was, but it's give away for me.
