### ISSUE TITLE
Update React to v0.13

### ISSUE THREAD

**Issue by pheuter** [pheuter/essential-react#5]

**Comment by paulyoung** [comment]
Are you planning on waiting until the beta tag is dropped?

**Comment by pheuter** [comment]
@paulyoung Hm, I was under the impression that the latest release[1] is not in beta.

[1] http://facebook.github.io/react/blog/2015/03/10/react-v0.13.html

**Comment by paulyoung** [comment]
You're right, I thought v0.13 Beta 1 was the latest.

**Comment by pheuter** [comment]
react-router currently requires react v0.12.x, so updating causes npm to throw an `EPEERINVALID`.

**Comment by pheuter** [comment]
Will be addressed in #11
