### ISSUE TITLE
Use fetch

### ISSUE THREAD

**Issue by nkt** [pheuter/essential-react#9]
Maybe you should replace `/common/request.js` by `fetch`?
https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent
There is polyfill: https://github.com/github/fetch

**Comment by pheuter** [comment]
Seems like `window.fetch` is a nicer way to do xhr with promises out of the box. I think devs who would like to implement this in their apps can easily include it as a dependency, but in the interest of depending on as few libraries as possible and keeping the skeleton minimal, I think it is fine to leave the basic XMLHttpRequest implementation in `/common/request.js`.
